---
title: "Dimension Reduction seperate for WS and RB"
author: "Clare"
date: "7/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(glmm)
library(plyr)
library(dbplyr)
```

```{r}
#regular code for the unreduced dataset

library(glmm)
data("salamander")

salamander
m<-10^3
clust<-makeCluster(4)
set.seed(1234)

ptm<-proc.time()
sal<-glmm(Mate~0+Cross,
          random = list(~0+Female,~0+Male),
          varcomps.names = c("F","M"), data=salamander,
          family.glmm = bernoulli.glmm, m=m, cluster = clust)
proc.time()-ptm
Beta<-sal$beta
```

```{r}
#Separating the Female and male id numbers into rough and white butts

F_R <- levels(salamander$Female)[1:10]
F_R <- append(F_R, levels(salamander$Female)[21:30])
F_R <- append(F_R, levels(salamander$Female)[41:50])
F_R

M_R <- levels(salamander$Male)[1:10]
M_R <- append(M_R, levels(salamander$Male)[21:30])
M_R <- append(M_R, levels(salamander$Male)[41:50])
M_R

F_W <- levels(salamander$Female)[11:20]
F_W <- append(F_W, levels(salamander$Female)[31:40])
F_W <- append(F_W, levels(salamander$Female)[51:60])
F_W

M_W <- levels(salamander$Female)[11:20]
M_W <- append(M_W, levels(salamander$Female)[31:40])
M_W <- append(M_W, levels(salamander$Female)[51:60])
M_W
```

```{r}
#separating the random errors for female and male white and rough butts

female<-sal$u.pql[1:60]
F_RPql <- female[1:10]
F_RPql <- append(F_RPql, female[21:30])
F_RPql <- append(F_RPql, female[41:50])
F_RPql

F_WPql <- female[11:20]
F_WPql <- append(F_WPql, female[31:40])
F_WPql <- append(F_WPql, female[51:60])
F_WPql

males<-sal$u.pql[61:120]
M_RPql <- males[1:10]
M_RPql <- append(M_RPql, males[21:30])
M_RPql <- append(M_RPql, males[41:50])
M_RPql

M_WPql <- males[11:20]
M_WPql <- append(M_WPql, males[31:40])
M_WPql <- append(M_WPql, males[51:60])
M_WPql
```

```{r}
library(glmm)
data("salamander")

F_R1<-data.frame(num= F_R)
F_W1<-data.frame(num=F_W)

#Dimension reduction for female rough and white butts separately
R_Female <- ReduceDim(F_R1$num, F_RPql)
NewR_F<-as.numeric(R_Female)+30
W_Female<-ReduceDim(F_W1$num, F_WPql)

#reduced dimensions for females
fLen10 <- length(levels(R_Female)) + length(levels(W_Female))

#creating a new list of the 60 females with their new ids
Fdata<-NewR_F[1:10]
Fdata<- append(Fdata, W_Female[1:10])
Fdata<- append(Fdata, NewR_F[11:20])
Fdata<- append(Fdata, W_Female[11:20])
Fdata<- append(Fdata, NewR_F[21:30])
Fdata<- append(Fdata, W_Female[21:30])
Fdata
```

```{r}
M_R1<-data.frame(num = M_R)
M_W1<-data.frame(num = M_W)

#dimension reduction for the male rough and white butts separately
R_Male <- ReduceDim(M_R1$num, M_RPql)
W_Male <- ReduceDim(M_W1$num, M_WPql)
NewR_M <- as.numeric(R_Male)+30

#reduced dimensions for males
mLen10 <- length(levels(R_Male))+ length(levels(W_Male))

#creating a new list of the 60 males with their new ids
Mdata<-NewR_M[1:10]
Mdata<- append(Mdata, W_Male[1:10])
Mdata<- append(Mdata, NewR_M[11:20])
Mdata<- append(Mdata, W_Male[11:20])
Mdata<- append(Mdata, NewR_M[21:30])
Mdata<- append(Mdata, W_Male[21:30])
Mdata
```

```{r}
#mapping the new list of male and female id's onto the salamander data
salamander$Female_Reduced1<-mapvalues(salamander$Female,c(10:69),Fdata)
salamander$Male_Reduced1<-mapvalues(salamander$Male, c(10:69), Mdata)
```

```{r}
#running the glmm on the data with the separate ids for rough and white butts
m<-10^3
clust<-makeCluster(4)
set.seed(1234)
ptm<-proc.time()
sal2<-glmm(Mate~0+Cross,
          random = list(~0+Female_Reduced1,~0+Male_Reduced1),
          varcomps.names = c("F","M"), data=salamander,
          family.glmm = bernoulli.glmm, m=m, cluster = clust)
proc.time()-ptm
DrBeta<-sal2$beta
```

```{r}
# Running the code but for no distinction b/w rb and ws
clust<-makeCluster(4)
set.seed(1234)
salamander$Female_Reduced<- ReduceDim(salamander$Female,sal$u.pql[1:60])
salamander$Male_Reduced<- ReduceDim(salamander$Male,sal$u.pql[61:120])
ptm<-proc.time()
sal1<-glmm(Mate~0+Cross,
          random = list(~0+Female_Reduced,~0+Male_Reduced),
          varcomps.names = c("F","M"), data=salamander,
          family.glmm = bernoulli.glmm, m=m, cluster = clust)
proc.time()-ptm
DrBeta0<-sal1$beta
```
```{r}
# Predicting with diff betas and u_s
betas<-data.frame(b0<-sal$beta,b1<-sal1$beta,b2<-sal2$beta)
prediction<-data.frame(c(1:360))
# Model 0 Predictions - No DR
prediction$p0<-expit(salamander$Cross %>% betas$b0[.] + salamander$Female %>% sal$u.pql[1:60][.] + salamander$Male %>% sal$u.pql[61:120][.])
# Model 1 Predictions -  DR on separate sexes
prediction$p1<-expit(salamander$Cross %>% betas$b1[.] + salamander$Female_Reduced %>% as.numeric() %>% sal1$u.pql[1:25][.] + salamander$Male_Reduced %>% as.numeric() %>% sal1$u.pql[25:50][.])
# Model 2 Predictions - DR on separate sexes and species
prediction$p2<-expit(salamander$Cross %>% betas$b2[.] + salamander$Female_Reduced1 %>% as.numeric() %>% sal2$u.pql[1:35][.] + salamander$Male_Reduced1 %>% as.numeric() %>% sal2$u.pql[36:72][.])
# Plotting the results

library(ggplot2)
g<-ggplot(data=prediction,aes(x=p0))+
  geom_point(aes(y=p1,color='Just Sexes(model 1)'),key_glyph    = draw_key_point)+
  geom_point(aes(y=p2,color='Sexes and Species(model 2)'),key_glyph =draw_key_point)+
  geom_abline(aes(slope=1,intercept=0,color='y=x'),key_glyph = draw_key_abline)+
  labs(color='Type of DR' ,title='Expit Function(p) under different DR conditions')+
  xlab('p without DR(model 0) ') +
  ylab('p with DR (model 1/2)')
ggsave('./plots/_dr_no_dr_less_dr.png', height = 10 , width = 10)
```

